version: '3.6'
services:
  postgres:
    image: postgres:9.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: hasura
      POSTGRES_USER: hasura
      POSTGRES_DB: hasura
  hasura:
    image: hasura/graphql-engine:v1.0.0-alpha40
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://hasura:hasura@postgres:5432/hasura
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
